- name: API deployment  
  hosts:  "{{ target }}"
  remote_user: ansible
  gather_facts: yes  
  become: true
  
  vars:
     PROCESS: "lala-micro"

  tasks:

   #- name: cleaning
    # shell: "ps -ef | grep -v grep | grep -w ssh | awk '{print $2}'"
    #register: running_processes
    #ignore_errors: True   

  - debug:
      msg: "This only displays with ansible-playbook -vv+"
      verbosity: 2    
   
  - name: Creating installation directory
    file:
      path: /etc/ExtractedJavaProject/
      state: directory

  - name: Installing- Unarchive a file that is already on the remote machine
    unarchive:
        src: /etc/javaProject/apache-maven-3.6.3-bin.tar.gz
        dest: /etc/ExtractedJavaProject/
        remote_src: yes
        keep_newer: yes
        owner: ansible
        group: ansible
        mode: 700

  - name: Get running processes 
    shell: "ps -ef | grep -v grep | grep -w {{ PROCESS }} | awk '{print $2}'"
    register: running_processes
    ignore_errors: yes

  - name: Kill running processes
    shell: "kill {{ item }}"
    with_items: "{{ running_processes.stdout_lines }}"
    ignore_errors: yes

  - wait_for:
      path: "/proc/{{ item }}/status"
      state: absent
    with_items: "{{ running_processes.stdout_lines }}"
    ignore_errors: yes
    register: killed_processes

  - name: Force kill stuck processes
    shell: "kill -9 {{ item }}"
    with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"
    ignore_errors: yes

  #- name: running
    
  
  roles:
          # - java
            
           
