- name: alhalla_m API deployment  
  hosts:  "{{ target }}"
  remote_user: ansible
  gather_facts: yes  
  become: true  
  connection: local
 
  vars:
       ssh_user_name: "ansible"     

  roles:       
       - java
       - monit
         # - nginx
       - nodejs
       - groovy
       - redis

