---

- name: Check if EPEL repo is already configured.
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel_repofile_result

- name: Import EPEL GPG key.
  rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install EPEL repo.
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

#- name: Enable EPEL Repository on CentOS 8
#  dnf:
#   name: epel-release
#   state: latest
#   when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] == '8'

- name: Enable EPEL Repository
  yum:
   name: epel-release
   state: present


- name: Install monit
  yum:
    name: monit
    state: present
  notify: Restart monit

