---
# variable file
#User config variables:
ssh_user_name: "ansible"

#Directory configurations
tarball_tmp_location: "/tmp" 
tarball_location: "{{ master_base_dir}}/"
tarball_name: "apache-maven-3.6.3-bin.tar.gz"
artifactory_path: "http://mirror.cogentco.com/pub/apache/maven/maven-3/3.6.3/binaries/"
managed_file_mode: "0700"
managed_conf_file_mode: "0666"
managed_monit_conf_file_mode: "0400"
branch:
revision:
fe_url:
alhalla_m_port:
alhalla_m_legacy_host:
alhalla_m_legacy_port:
alhalla_m_environment:

# Enable debug mode to receive more logs
alhalla_m_enable_debug: true

# Valhalla db configs
alhalla_m_alhalla_web_db_server: 'web-postgrey-server'
alhalla_m_alhalla_web_db_name: 'web-postgrey'
alhalla_m_alhalla_web_db_port: "5432"
alhalla_m_alhalla_web_db_user: "{{ vault_alhalla_m_alhalla_web_db_user }}"
alhalla_m_alhalla_web_db_password: "{{ vault_alhalla_m_alhalla_web_db_password }}"


alhalla_m_aux_mdm_db_server: 'aux-mdm-server'
alhalla_m_aux_mdm_db_name: 'aux-mdm-db'

alhalla_m_aux_mdm_db_user: "{{ vault_alhalla_m_aux_mdm_db_user }}"
alhalla_m_aux_mdm_db_password: "{{ vault_alhalla_m_aux_mdm_db_password }}"

# Security Configs
#alhalla_m_encryption_key: "{{ vault_alhalla_m_encryption_key }}"
#alhalla_m_encryption_init_vector: "{{ vault_alhalla_m_encryption_init_vector }}"
alhalla_m_jwt_signing_key: "{{ vault_alhalla_m_jwt_signing_key }}"
alhalla_sendgrid_api_key: "{{ vault_alhalla_sendgrid_api_key }}"

# Proxy stuff
http_proxy_host:
http_proxy_port:
https_proxy_host:
https_proxy_port:
no_proxy:

#java_opt: "-Denvironment=${alhalla_m_environment} -Dhttp.proxyHost=${http_proxy_host} -Dhttp.proxyPort=${http_proxy_port} -Dhttps.proxyHost=${https_proxy_host} -Dhttps.proxyPort=${https_proxy_port} -Dhttp.nonProxyHosts=\"${no_proxy}\""

#if $alhalla_m_enable_debug {
 #   $runCmd = "JAVA_HOME=/opt/orange/openjdk11 ALHALLA_M_OPTS='${java_opt}' ./bin/alhalla-m -d"
#} else {
#    $runCmd = "JAVA_HOME=/opt/orange/openjdk11 ALHALLA_M_OPTS='${java_opt}' ./bin/alhalla-m"
#  }

# Directory config
master_base_dir: "/opt/orange"
base_dir: "{{ master_base_dir }}/alhalla-m"
run_dir: "{{ master_base_dir }}/alhalla-m-run"
ansible_bin_files: "{{ master_base_dir }}/api-binary-files"
monit_config_dir: "/etc/monit.d"
bash_executable_path: "/usr/bin/bash"
api_conf_file_dir: "{{base_dir}}/conf"
api_datasources_conf_dir: "{{ api_conf_file_dir }}/datasources"
api_auth_conf_dir: "{{ api_conf_file_dir }}/auth"


#Template Configuration

#for init.sh

identifier: "alhalla_m"
pidfile: "{{ run_dir }}/alhalla_m.pid"
command: "{{ run_dir }}"
logfile: "{{ run_dir }}/console.out"
startWaitTime: 1
stopWaitTime: 4
cwd: "{{ base_dir }}"

#monit config
monit_identifier: "alhalla_m"
location: "{{base_dir}}/init.sh"
monit_timeout: 5
