---
# tasks file for java
- include: "{{ ansible_os_family }}.yml"

- name: Find path for new JAVA binary
  shell: update-alternatives --query java | grep Alternative | grep openjdk | grep -m 1 -e 'java-\(1\.\)\{0,1\}{{java_version}}' | cut -f 2 -d " "
  register: java_bin_path
  changed_when: false
  when: java_register_alternative

- name: Update alternatives to point to new JAVA installation
  alternatives: name=java path="{{java_bin_path.stdout}}"
  when: java_register_alternative

- name: Find path for new JAVA HOME
  shell: "echo $(dirname $(dirname $(readlink $(readlink $(which javac)))))"
  register: JAVA_HOME_PATH

- name: "loop through list"
  debug:
    msg: "An item: {{ item }}"
  with_items: "{{ JAVA_HOME_PATH.stdout_lines }}"

- name: Register JAVA_HOME env variable
  lineinfile: 
        dest: "/etc/profile"
        regexp: "^(export JAVA_HOME=)" 
        state: present 
        line: "export JAVA_HOME={{ item  }}"
  with_items: "{{ JAVA_HOME_PATH.stdout_lines }} "
  when: java_register_env

- name: Register java binary path in PATH  env variable
  lineinfile:
        dest: "/etc/profile"
        regexp: "^(export PATH=)"
        state: present
        line: "export PATH=$JAVA_HOME/bin:$PATH"
  when: java_register_env
